indent_style = "Block"
use_small_heuristics = "Max"
binop_separator = "Front"
combine_control_expr = true
comment_width = 150
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
error_on_line_overflow = false
error_on_unformatted = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = false
enum_discrim_align_threshold = 0
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
hard_tabs = true
imports_indent = "Block"
imports_layout = "Horizontal"
merge_imports = true
match_block_trailing_comma = true
max_width = 150
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Never"
report_fixme = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = false
wrap_comments = true
match_arm_blocks = true
overflow_delimited_expr = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
# required_version
hide_parse_errors = false
color = "Auto"
unstable_features = true
# license_template_path
ignore = []
edition = "2018"
version = "Two"
normalize_doc_attributes = true
inline_attribute_width = 0
# emit_mode
# make_backup
